### ISSUE TITLE
ConvertTo-Bicep throws error when running with no parameters.

### ISSUE THREAD

**Issue by bjompen** [StefanIvemo/BicepPowerShell#190]
**Describe the bug**
If running `ConvertTo-Bicep` with no parameters, inside a folder with a ARM template file, it will correctly perform the conversion, but it will also throw an error.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17783007/122984652-89ca6100-d39d-11eb-90ac-2648e8c609cc.png)

**To Reproduce**
```PowerShell
cd c:\folderWithArmFiles
gci # No bicep file is there
ConvertTo-Bicep
gci # bicep file is created
```
**Expected behavior**
Convertsion should be performed as it currently is, but no error should be thrown.

**Additional context**
```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Get-Module bicep

ModuleType Version    PreRelease Name 
---------- -------    ---------- ---- 
Script     1.5.0                 bicep
```

**Comment by StefanIvemo** [comment]
It looks like the issue here is that it tries to convert the parameter file in the folder to a bicep file. The error messages states that the schema `"$schema": "https://schema.management.azure.com/schemas/<API Version>/deploymentParameters.json#"` did not  match any of the known ARM template deployment schemas, which is true. The decompile function only works for ARM templates.

The fix for this should be to validate that the file to decompile is an ARM template by verifying the schema. One could also argue that this is a valid error.
